# Generated by Django 3.2.7 on 2022-01-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='innerPortPageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=30)),
                ('rowFormat', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=200)),
                ('portimg1', models.ImageField(blank=True, default='none.jpg', null=True, upload_to='')),
                ('portimg2', models.ImageField(blank=True, default='none.jpg', null=True, upload_to='')),
                ('portimg3', models.ImageField(blank=True, default='none.jpg', null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Portfolio inner page items',
            },
        ),
        migrations.CreateModel(
            name='portfolioPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portName', models.CharField(max_length=30)),
                ('img1', models.ImageField(upload_to='portfolio')),
                ('img2', models.ImageField(upload_to='portfolio')),
                ('img3', models.ImageField(upload_to='portfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio IMG pages',
            },
        ),
    ]
