# Generated by Django 3.2.9 on 2021-12-16 14:31

import Sitemanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addImg4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('pre-1', 'pre-1'), ('pre-2', 'pre-2'), ('pre-3', 'pre-3'), ('pre-4', 'pre-4')], max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to=Sitemanager.models.addImg4.uploadFolder)),
                ('img2', models.ImageField(upload_to=Sitemanager.models.addImg4.uploadFolder)),
                ('img3', models.ImageField(upload_to=Sitemanager.models.addImg4.uploadFolder)),
                ('img4', models.ImageField(upload_to=Sitemanager.models.addImg4.uploadFolder)),
                ('txt', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Format 4 foto's",
            },
        ),
        migrations.CreateModel(
            name='addImg5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portName', models.CharField(choices=[('creatief', 'creatief'), ('dieren', 'dieren'), ('ethiopië', 'ethiopië'), ('evenementen', 'evenementen'), ('gebouwen', 'gebouwen'), ('kids', 'kids'), ('schilderijen', 'schilderijen'), ('tieners', 'tieners'), ('volwassenen', 'volwassenen'), ('voorstellingen', 'voorstellingen')], max_length=100)),
                ('alignment', models.CharField(choices=[('left', 'left'), ('right', 'right'), ('center', 'center'), ('up', 'up'), ('down', 'down')], max_length=100)),
                ('img1', models.ImageField(upload_to='portfolio')),
                ('img2', models.ImageField(upload_to='portfolio')),
                ('img3', models.ImageField(upload_to='portfolio')),
                ('img4', models.ImageField(upload_to='portfolio')),
                ('img5', models.ImageField(upload_to='portfolio')),
                ('txt', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Format 5 foto's",
            },
        ),
        migrations.CreateModel(
            name='portfolioPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portName', models.CharField(max_length=30)),
                ('img1', models.ImageField(upload_to='portfolio')),
                ('img2', models.ImageField(upload_to='portfolio')),
                ('img3', models.ImageField(upload_to='portfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio IMG pages',
            },
        ),
    ]
