# Generated by Django 3.2.7 on 2021-11-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shootPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(choices=[('Event shoot', 'Event shoot'), ('Portret shoot', 'Portret shoot'), ('Familie shoot', 'Familie shoot'), ('Dieren shoot', 'Dieren shoot'), ('Gebouwen shoot', 'Gebouwen shoot')], max_length=25)),
                ('Alinea1', models.TextField()),
                ('Alinea2', models.TextField()),
                ('Alinea3', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Tarieven',
            },
        ),
    ]
