# Generated by Django 3.2.7 on 2022-01-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innerportpageitems',
            name='portimg4',
            field=models.ImageField(blank=True, default='none.jpg', null=True, upload_to=''),
        ),
    ]
