# Generated by Django 3.2.7 on 2021-12-17 19:12

import Sitemanager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimg5',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='addimg5',
            name='portName',
        ),
        migrations.AddField(
            model_name='addimg5',
            name='preset',
            field=models.CharField(choices=[('pre-1', 'pre-1'), ('pre-2', 'pre-2'), ('pre-3', 'pre-3'), ('pre-4', 'pre-4')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addimg5',
            name='title',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addimg5',
            name='img1',
            field=models.ImageField(upload_to=Sitemanager.models.addImg5.uploadFolder),
        ),
        migrations.AlterField(
            model_name='addimg5',
            name='img2',
            field=models.ImageField(upload_to=Sitemanager.models.addImg5.uploadFolder),
        ),
        migrations.AlterField(
            model_name='addimg5',
            name='img3',
            field=models.ImageField(upload_to=Sitemanager.models.addImg5.uploadFolder),
        ),
        migrations.AlterField(
            model_name='addimg5',
            name='img4',
            field=models.ImageField(upload_to=Sitemanager.models.addImg5.uploadFolder),
        ),
        migrations.AlterField(
            model_name='addimg5',
            name='img5',
            field=models.ImageField(upload_to=Sitemanager.models.addImg5.uploadFolder),
        ),
    ]
