# Generated by Django 3.2.7 on 2021-11-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shootPayment',
        ),
    ]
