# Generated by Django 3.0.8 on 2021-12-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0003_addimg4_addimg5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addimg4',
            old_name='portName',
            new_name='portNameChoice',
        ),
        migrations.RenameField(
            model_name='addimg5',
            old_name='portName',
            new_name='portNameChoice',
        ),
    ]
