# Generated by Django 3.2.7 on 2022-01-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitemanager', '0006_auto_20220110_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innerportpageitems',
            old_name='pageName',
            new_name='portName',
        ),
    ]
