# Generated by Django 3.2.7 on 2022-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(default='Contact info', max_length=25)),
                ('place', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('socials', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='shootPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(choices=[('Event shoot', 'Event shoot'), ('Portret shoot', 'Portret shoot'), ('Familie shoot', 'Familie shoot'), ('Dieren shoot', 'Dieren shoot'), ('Gebouwen shoot', 'Gebouwen shoot')], max_length=25)),
                ('Alinea1', models.TextField(default='none')),
                ('Alinea2', models.TextField(default='none')),
                ('Alinea3', models.TextField(default='none')),
            ],
            options={
                'verbose_name_plural': 'Tarieven',
            },
        ),
    ]
