# Generated by Django 3.2.9 on 2021-11-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootpayment',
            options={'verbose_name_plural': 'shootPayment'},
        ),
    ]
