# Generated by Django 3.2.9 on 2021-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_shootpayment_titeldb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shootpayment',
            options={'verbose_name_plural': 'Tarieven'},
        ),
        migrations.RemoveField(
            model_name='shootpayment',
            name='titelDB',
        ),
        migrations.AlterField(
            model_name='shootpayment',
            name='titel',
            field=models.CharField(choices=[('Event shoot', 'Event shoot'), ('Portret shoot', 'Portret shoot'), ('Familie shoot', 'Familie shoot'), ('Dieren shoot', 'Dieren shoot'), ('Gebouwen shoot', 'Gebouwen shoot')], max_length=25),
        ),
    ]
