# Generated by Django 3.2.9 on 2021-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20211111_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shootpayment',
            old_name='context',
            new_name='Alinea1',
        ),
        migrations.AddField(
            model_name='shootpayment',
            name='Alinea2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shootpayment',
            name='Alinea3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
