# Generated by Django 3.2.7 on 2021-11-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shootpayment',
            name='alinea1Align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shootpayment',
            name='alinea2Align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shootpayment',
            name='alinea3Align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shootpayment',
            name='Alinea1',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='shootpayment',
            name='Alinea2',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='shootpayment',
            name='Alinea3',
            field=models.TextField(default='none'),
        ),
    ]
