# Generated by Django 3.2.7 on 2021-11-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20211112_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shootpayment',
            name='alinea1Align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=200),
        ),
        migrations.AlterField(
            model_name='shootpayment',
            name='alinea2Align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=200),
        ),
        migrations.AlterField(
            model_name='shootpayment',
            name='alinea3Align',
            field=models.CharField(choices=[('left', 'left'), ('center', 'center'), ('right', 'right')], default='left', max_length=200),
        ),
    ]
